#!/usr/bin/env bash
MODULE="equinox"

LUAROCKS_BIN=$(which lua)
if [ -z "$LUAROCKS_BIN" ]; then
  echo "Lua is not installed. Equinox requires Lua."
  exit 1
fi

EXT_DIR="$(luarocks show --rock-dir $MODULE)/ext"
MODULE_PATH=$(luarocks show --porcelain "$MODULE" | grep "bundle" | awk -F' ' '{print $3}')

EQUINOX_EXT_DIR="$EXT_DIR" $LUAROCKS_BIN "$MODULE_PATH" "$@"
