name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.1.5"
    - uses: leafo/gh-actions-luarocks@v4
        
    - name: Install dependencies
      run: |
        luarocks install luacov
        luarocks install luacov-coveralls
        
    - name: Check Lua
      run: |
        lua -v
        which lua
        luarocks list
        lua -e 'print(require("luacov"))'
        ls -al
      
    - name: Run tests
      run: |
        LUA_PATH=/home/runner/work/equinox/equinox/.luarocks:$LUA_PATH make coverage
