name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.4"

    - name: Run check
      run: make test
