name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.4"
        
    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v4.3.0
      with:
        luaRocksVersion: 3.8.0

    - name: Install dependencies
      shell: bash
      run: |
        sudo ./.luarocks/bin/luarocks install luacov
        
    - name: Check Lua
      run: lua -v

    - name: Check cwd
      run: ls -al
      
    - name: Run tests
      run: make test
